### ISSUE TITLE
YAML configuration support

### ISSUE THREAD

**Issue by tperale** [Sprtch/erie#1]
The configuration should have the following structure

```
erie:
    redis: "victoria"
    devices:
        - symbolfz:
            type: "serial"
            id: "usb-FTDI_FT232R_USB_UART_A9UXOL6H-if00-port0"
            baudrate: 9600
        - inatek:
            type: "evdev"
            id: "usb-Belon.cn_2.4G_Wireless_Device_Belon_Smart-event-kbd"
```

Must allow to declare multiple devices of different types with the different configurations. Possibly also allow to send the message from the different scanner to different redis channel.
